config/routes.rb
Githacking::Application.routes.draw do
  root to: "pages#home"
  
  match "about" => 'pages#about'
  match "faq" => 'pages#faq'
  match "terms" => 'pages#terms'
  match "privacy" => 'pages#privacy'

  match '/users/oauth' => 'users#create', as: 'oauth_callback'

  resource :user_session
  match '/logout' => 'user_sessions#destroy', as: 'logout'
  match '/login' => 'user_sessions#new', as: 'login'

  # GitHub reserves /account for user account settings, so we can take
  # advantage of that for our own logged in user page.
  resource :account, controller: 'users'
  resources :users, path: ''  do
    # Doing `resources :repositories` here screws with users routing,
    # and we don't need anything but show for repositories anyway
    constraints id: /[^\/]+/ do
      get '/:id' => 'repositories#show', as: 'repository'
      get '/:repository_id/issues(/:tag)' => 'repositories#issues', as: 'repository_issues'
    end
  end

  # Have to do this outside the nested resource so we get reasonable
  # named route generation without using `resources :metadata`
  get '/:user_id/:repository_id/metadata/new' => 'metadata#new', as: 'new_user_repository_metadata'
  get '/:user_id/:repository_id/metadata/edit' => 'metadata#edit', as: 'edit_user_repository_metadata'
  post '/:user_id/:repository_id/metadata' => 'metadata#create', as: 'user_repository_metadata'

end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  acts_as_authentic do |c|
    # email field is not always populated in a github account
    c.validate_email_field false
  end

  validates_presence_of :github_access_token
  
  def repositories(load_associations=true)
    return @repository_stubs if defined?(@repository_stubs)
    @repository_stubs = []
    Octopi::User.find(self.login).repositories.each do |remote_repository|
      # build local repos, don't bother loading languages
      @repository_stubs << Repository.from_github_to_domain(remote_repository, load_associations)
    end
    @repository_stubs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def create
    url = 'https://github.com/login/oauth/access_token'
    query = 'client_id=' + Github.config[:client_id] + 
      '&redirect_uri=' + Github.config[:redirect_uri] + 
      '&client_secret=' + Github.config[:secret] + 
      '&code=' + params[:code]
    
    token_response = Curl::Easy.http_post(url, query).body_str
    if token_response.empty?
      flash[:notice] = 'GitHub didn\'t respond. Try again?'
      redirect_to login_path and return
    end
    token = token_response.split('=')[1]
    
    url = 'https://github.com/api/v2/json/user/show?access_token=' + token
    data = JSON::parse(Curl::Easy.http_get(url).body_str)['user']

    @user = User.where(email: data['email']).first

    # Login if the user exists
    unless @user.nil?
      @user_session = UserSession.create(@user)
      redirect_back_or_default(root_url)
      return
    end

    @user = User.new(login: data['login'], email: data['email'], github_access_token: token)
    if @user.save
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/views/users/_form.html.haml
= form.label :login
%br
= form.text_field :login
%br
%br
= form.label :password, form.object.new_record? ? nil : "Change password"
%br
= form.password_field :password
%br
%br
= form.label :password_confirmation
%br
= form.password_field :password_confirmation
%br
%br
= form.label :github_key, 'Github API key'
%br
= form.text_field :github_key
%br
%br

app/views/users/edit.html.haml
%h1 Edit My Account
= form_for @user, :url => account_path do |f|
  = render :partial => "form", :object => f
  = f.submit "Update"
  %br
= link_to "My Profile", account_path

app/views/users/new.html.haml
%h1 Register
= link_to 'Log in to Github', 'https://github.com/login/oauth/authorize?client_id=' + Github.config[:client_id] + '&redirect_uri=' + Github.config[:redirect_uri]

app/views/users/show.html.haml
:erb
  <p>
    <%= image_tag @user.gravatar_url %>
  </p>
  <p>
    <b>Login:</b>
    <%=h @user.login %>
  </p>
  
  <p>
    <b>Login count:</b>
    <%=h @user.login_count %>
  </p>
  
  <p>
    <b>Last request at:</b>
    <%=h @user.last_request_at %>
  </p>
  
  <p>
    <b>Last login at:</b>
    <%=h @user.last_login_at %>
  </p>
  
  <p>
    <b>Current login at:</b>
    <%=h @user.current_login_at %>
  </p>
  
  <p>
    <b>Last login ip:</b>
    <%=h @user.last_login_ip %>
  </p>
  
  <p>
    <b>Current login ip:</b>
    <%=h @user.current_login_ip %>
  </p>
  
  
  <%= link_to 'Edit', edit_account_path %>