config/routes.rb
Githacking::Application.routes.draw do
  root to: "pages#home"
  
  match "about" => 'pages#about'
  match "faq" => 'pages#faq'
  match "terms" => 'pages#terms'
  match "privacy" => 'pages#privacy'

  match '/users/oauth' => 'users#create', as: 'oauth_callback'

  resource :user_session
  match '/logout' => 'user_sessions#destroy', as: 'logout'
  match '/login' => 'user_sessions#new', as: 'login'

  # GitHub reserves /account for user account settings, so we can take
  # advantage of that for our own logged in user page.
  resource :account, controller: 'users'
  resources :users, path: ''  do
    # Doing `resources :repositories` here screws with users routing,
    # and we don't need anything but show for repositories anyway
    constraints id: /[^\/]+/ do
      get '/:id' => 'repositories#show', as: 'repository'
      get '/:repository_id/issues(/:tag)' => 'repositories#issues', as: 'repository_issues'
    end
  end

  # Have to do this outside the nested resource so we get reasonable
  # named route generation without using `resources :metadata`
  get '/:user_id/:repository_id/metadata/new' => 'metadata#new', as: 'new_user_repository_metadata'
  get '/:user_id/:repository_id/metadata/edit' => 'metadata#edit', as: 'edit_user_repository_metadata'
  post '/:user_id/:repository_id/metadata' => 'metadata#create', as: 'user_repository_metadata'

end

app/views/shared/_content.html.haml
.container
  = yield

app/views/shared/_footer.html.haml
#footer
  .container
    #footer-container
      #footer-navigation
        = link_to('Home', root_path)
        \/
        = link_to('About', about_path)
        \/
        = link_to('Blog', "http://blog.gethacking.com")
        \/
        = link_to('FAQ', faq_path)
        \/
        = link_to('Terms', terms_path)
        \/
        = link_to('Privacy', privacy_path)

app/views/shared/_header.html.haml
.container
  #logo.span-16
    = image_tag("terminal.png")
    %h1
      = link_to("git hacking", root_path)
      %span
        make contributing easier
  = render :partial => "shared/navigation"

app/views/shared/_navigation.html.haml
#main-navigation.span-8.last
  %ul
    - if current_user
      %li
        = link_to 'Dashboard', root_path
      %li
        = link_to 'Log out', logout_path
    - else
      %li
        = link_to 'Log in with Github', github_login_url