config/routes.rb
Githacking::Application.routes.draw do
  root to: "pages#home"
  
  match "about" => 'pages#about'
  match "faq" => 'pages#faq'
  match "terms" => 'pages#terms'
  match "privacy" => 'pages#privacy'

  match '/users/oauth' => 'users#create', as: 'oauth_callback'

  resource :user_session
  match '/logout' => 'user_sessions#destroy', as: 'logout'
  match '/login' => 'user_sessions#new', as: 'login'

  # GitHub reserves /account for user account settings, so we can take
  # advantage of that for our own logged in user page.
  resource :account, controller: 'users'
  resources :users, path: ''  do
    # Doing `resources :repositories` here screws with users routing,
    # and we don't need anything but show for repositories anyway
    constraints id: /[^\/]+/ do
      get '/:id' => 'repositories#show', as: 'repository'
      get '/:repository_id/issues(/:tag)' => 'repositories#issues', as: 'repository_issues'
    end
  end

  # Have to do this outside the nested resource so we get reasonable
  # named route generation without using `resources :metadata`
  get '/:user_id/:repository_id/metadata/new' => 'metadata#new', as: 'new_user_repository_metadata'
  get '/:user_id/:repository_id/metadata/edit' => 'metadata#edit', as: 'edit_user_repository_metadata'
  post '/:user_id/:repository_id/metadata' => 'metadata#create', as: 'user_repository_metadata'

end

app/controllers/metadata_controller.rb
class MetadataController < ApplicationController
  def new
  end

  def create
    send_file Repository::Metadata.new(params[:metadata]).to_file, type: 'application/x-yaml'
  end

  def edit
  end

end

app/helpers/metadata_helper.rb
module MetadataHelper
end

app/views/metadata/_form.html.haml
.label

app/views/metadata/edit.html.haml
%h1 Metadata#edit
%p Find me in app/views/metadata/edit.html.haml

app/views/metadata/new.html.haml
- content_for :javascripts do
  = javascript_include_tag 'metadata'

#new-metadata-form
  = form_tag user_repository_metadata_path do
    .label
      = label_tag 'metadata[long_description]', 'Long Description'
    .field
      = text_area_tag 'metadata[long_description]'
    .label
      = label_tag 'metadata[categories][]', 'Categories'
    #categories
      -# This markup is mirrored in metadata.js. Be sure to keep both
      -# places consistent!
      .field.category
        = text_field_tag 'metadata[categories][]'
    %h3
      Needs
    .label
      = label_tag 'metadata[needs][roles][]', 'Roles'
    #roles
      -# This markup is mirrored in metadata.js. Be sure to keep both
      -# places consistent!
      .field.role
        Name:
        = text_field_tag 'metadata[needs][roles][][role]', nil, class: 'role-role'
        %br
        Language: 
        = text_field_tag 'metadata[needs][roles][][langauge]', nil, class: 'role-language'
        %br
        Description:
        = text_field_tag 'metadata[needs][roles][][description]', nil, class: 'role-description'
    .label
      = label_tag 'metadata[mentions][]', 'Mentions'
    #mentions
      .field.mention
        = text_field_tag 'metadata[mentions][]'
    = submit_tag 'Generate'
  